### PR TITLE
Creating a Seamless World

### PR DESCRIPTION
**Pull request by SeraphWedd**
I nipped and edited two lines from your code to make the world Seamless. Please check.

### CODE REVIEW

**Comment by nicoloridulfo** [comment]
That is cool! I'll accept this change!

But first, could I just ask you a question (as it seems that you have experience with pygame):

Is there a way that the drawing performance could be increased? I would like to run this program with a 1000x1000 grid. Currently that results in less than 1 FPS...

**Comment by SeraphWedd** [comment]
There are some optimizations that can be done with pygame but the effect would be minimal. The most time consuming part of the code is the one using numba, which sweeps through all the array's cell for creating a new array. So, to speed up the processing, I can think of 2 ways to do it.

1. Use multi-threading to split the work on creating the newGrid. Though single-threaded CPU's will not benefit from this.

2. Optimize the code used for the function nextGenerationCalculation. I think there are a lot of ways to do this faster with numpy.

I am currently considering the no. 2. option. I will pull once more when I'm done.

**Comment by nicoloridulfo** [comment]
I don't think that the problem lies in the the numba-code as it should be extremely fast now.

I benchmarked the main loop by adding the following code to benchmark:
``` Python
t0 = time.time() #<-------------------------
display.fill((0, 0, 0))
for event in pg.event.get():
    if event.type == pg.QUIT:
        running = False
for row in range(ROWS):
    for column in range(COLUMNS):
        if life.grid[column][row]==1:
            pg.draw.rect(display, (255, 255, 255), (squareSide*column, squareSide*row, squareSide, squareSide))
text = font.render(f"FPS: {round(1/(time.time()-lastTime))}",True, (255,255,255))
lastTime = time.time()
display.blit(text, (0,0))
pg.display.update()
t1 = time.time()#<-------------------------
life.nextGeneration()
t2 = time.time()#<-------------------------
print("Drawing: ", t1-t0, "Next generation:", t2-t1)#<-------------------------
```
This game me the following results:
Drawing:  0.04296469688415527 Next generation: 0.00099945068359375
Drawing:  0.04297137260437012 Next generation: 0.0009984970092773438
Drawing:  0.042966365814208984 Next generation: 0.000997781753540039

The majority of the time is spent drawing. I believe the reason is getting the values from the numpy ndarray (I hypothesized this in the README).
By getting the ndarray in a bulk operation making the following changes:
``` Python
t0 = time.time()
display.fill((0, 0, 0))
for event in pg.event.get():
    if event.type == pg.QUIT:
        running = False
pythonGrid = life.grid.tolist()#<-------------------------
for row in range(ROWS):
    for column in range(COLUMNS):
        if pythonGrid[column][row]==1:
            pg.draw.rect(display, (255, 255, 255), (squareSide*column, squareSide*row, squareSide, squareSide))
text = font.render(f"FPS: {round(1/(time.time()-lastTime))}",True, (255,255,255))
lastTime = time.time()
display.blit(text, (0,0))
pg.display.update()
t1 = time.time()
life.nextGeneration()
t2 = time.time()
print("Drawing: ", t1-t0, "Next generation:", t2-t1)
```
This small changed resulted in a doubling in speed:
Drawing:  0.02398085594177246 Next generation: 0.0009992122650146484
Drawing:  0.02198171615600586 Next generation: 0.0019989013671875
Drawing:  0.02198171615600586 Next generation: 0.0019989013671875

I do not know what could be done to shave of the remaining time drawing.

**Comment by nicoloridulfo** [comment]
I'll merge the pull request in the meantime. Please open a new one if you have more code to contribute.
Thanks for the help so far! :)

**Comment by SeraphWedd** [comment]
I see.
I found a possible replacement for the whole drawing of the array. Although for some reason, it turned black and blue instead of black and white. Either way, here:

Instead of:
```

        for row in range(ROWS):
            for column in range(COLUMNS):
                if life.grid[column][row]==1:
                    pg.draw.rect(display, (255, 255, 255), (squareSide*column, squareSide*row, squareSide, squareSide))
```

Try:
```
game_surf = pg.surfarray.make_surface(life.grid)
game_surf = pg.transform.scale(game_surf, (WIN_SIZE, WIN_SIZE))
display.blit(game_surf, (0, 0))
```

Where WIN_SIZE is the dimension of your screen.

**Pull request merged**
